# Site settings
title: The SAT Museum 
email: satmuseum@satlive.org 
description: > # this means to ignore newlines until "baseurl:"
  The SAT museum is a web site dedicated to hosting the source code of
  historic SAT solvers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://satmuseum.github.io" # the base hostname & protocol for your site
github_username: satmuseum 

# Build settings
markdown: kramdown
